blank_issues_enabled: false
contact_links:
  - name: Feature Request or Idea
    url: https://github.com/php/pie/discussions/new?category=ideas
    about: For new features or suggestions, please open a Discussion
