<?php

declare(strict_types=1);

namespace Php\Pie\Platform;

use Symfony\Component\Process\Process;

use function assert;
use function file_exists;
use function is_executable;
use function Safe\preg_match;
use function trim;

/** @internal This is not public API for PIE, so should not be depended upon unless you accept the risk of BC breaks */
final class MakePath
{
    private static function looksLikeValidGnuMake(string $makePathToCheck): bool
    {
        if ($makePathToCheck === '') {
            return false;
        }

        if (! file_exists($makePathToCheck) || ! is_executable($makePathToCheck)) {
            return false;
        }

        $makeVersionProcess = new Process([$makePathToCheck, '--version']);
        if ($makeVersionProcess->run() !== 0) {
            return false;
        }

        return preg_match('/GNU Make/i', $makeVersionProcess->getOutput()) === 1;
    }

    /**
     * PHP extension Makefiles (generated by phpize/configure) rely on GNU
     * Make syntax. On some platforms (e.g. FreeBSD, NetBSD, OpenBSD), the
     * `make` found on the PATH is the native BSD make, which cannot parse
     * these Makefiles; GNU Make is available there as `gmake` instead.
     *
     * @return non-empty-string
     */
    public static function guess(): string
    {
        foreach (['make', 'gmake'] as $candidate) {
            // Note: depends on `which` existing, which doesn't always...
            $which = new Process(['which', $candidate]);
            if ($which->run() !== 0) {
                continue;
            }

            $candidatePath = trim($which->getOutput());

            if (! self::looksLikeValidGnuMake($candidatePath)) {
                continue;
            }

            assert($candidatePath !== '');

            return $candidatePath;
        }

        // Fall back to assuming/hoping make is on the path
        return 'make';
    }
}
